name: gost # you probably want to 'snapcraft register <name>'
version: '2.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: GO Simple Tunnel
description: |
  A simple tunnel written in golang

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  gost:
    command: bin/gost
    plugs: [network, network-bind, home]

parts:
  gost:
    source: .
    # See 'snapcraft plugins'
    plugin: go
    go-packages: [github.com/ginuerzh/gost/cmd/gost]
    go-importpath: github.com/ginuerzh/gost
  go:
    source-tag: go1.8.3
