name: gost
type: app
version: '2.8.2'
title: GO Simple Tunnel
summary: A simple security tunnel written in golang
description: |
  https://github.com/ginuerzh/gost
confinement: strict
grade: stable
base: core18
license: MIT
parts:
  gost:
    plugin: nil
    build-snaps: [go/1.13/stable]
    source: https://github.com/ginuerzh/gost.git
    source-subdir: cmd/gost
    source-type: git
    source-branch: '2.8'
    build-packages:
      - build-essential
    build-environment:
    - GO111MODULE: 'on'
    override-build: |
      set -ex

      echo "Starting override-build:"
      pwd
      cd $SNAPCRAFT_PART_BUILD
      GO111MODULE=on go build
      ./gost -V

      echo "Installing to ${SNAPCRAFT_PART_INSTALL}..."
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -v gost $SNAPCRAFT_PART_INSTALL/bin/
apps:
  gost:
    command: bin/gost
    plugs: 
      - home
      - network
      - network-bind

