name: gost
type: app
version: '2.8.2'
title: GO Simple Tunnel
summary: A simple security tunnel written in golang
description: |
  https://github.com/ginuerzh/gost
confinement: strict
grade: stable
base: core18
license: MIT
parts:
  gost:
    plugin: go
    go-packages: [github.com/ginuerzh/gost/cmd/gost]
    source: https://github.com/ginuerzh/gost.git
    source-type: git
    source-branch: '2.8'
    build-packages:
      - build-essential
  
apps:
  gost:
    command: bin/gost
    plugs: 
      - home
      - network
      - network-bind

